apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: 624676053835.dkr.ecr.ap-northeast-2.amazonaws.com/demo-frontend
  newName: 624676053835.dkr.ecr.ap-northeast-2.amazonaws.com/demo-frontend
  newTag: "5.0"
resources:
- ../../base
patchesStrategicMerge:
- front-deployment-patch.yaml
